# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 80e7f5092965eab5204da5640b23e7c2cd82a4605e22dc55ad0bbc75908eb6913efa8e6e480c35b0f7297a6c0a0b2084b178a0df39cae0ee19cabcc0c0905956

test:
  secret_key_base: aa49e4a40ede9add7b606cedad6586adfa73710d013147711bb733d494b2a07451ea780819e8438ad63853af2ec79038e0b898cd293b20c66985a76b949d4b4f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
